version: "2"
services:
  server:
    container_name: gfip_server
    command: node app.js
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile-prod
    volumes:
      - .:/usr/src/app/
    env_file: .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  client:
    container_name: gfip_client
    build: 
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_ADDRESS=http://gfip.cin.ufpe.br:8080
    depends_on:
      - server
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
