version: "2"
services:
  server:
    container_name: app_server
    command: nodemon app.js
    restart: always
    build: .
    volumes:
      - .:/usr/src/app/
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links:
      - mongo
  client:
    container_name: app_client
    restart: always
    command: npm start
    build: ./client
    volumes:
      - ./client:/usr/src/app/
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - server
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"