version: "2"
services:
  server:
    container_name: gfip_server
    command: node app.js
    restart: always
    build: 
      context: ./server
      dockerfile: Dockerfile-prod
    volumes:
      - .:/usr/src/app/
    env_file: .env.prod
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    links:
      - mongo
  client:
    container_name: gfip_client
    build: 
      context: ./client
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    environment:
      - REACT_APP_API_ADDRESS=http://gfip.cin.ufpe.br:8080
    depends_on:
      - server
    volumes:
      - ./client/certbot/conf:/etc/letsencrypt
      - ./client/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot
    volumes:
      - ./client/certbot/conf:/etc/letsencrypt
      - ./client/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
